### ISSUE TITLE
Global Register of Introduced and Invasive Species - US (contiguous) & Alaska, US show the same number of occurences

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3969]
**Global Register of Introduced and Invasive Species - US (contiguous) &amp; Alaska, US show the same number of occurences**

Global Register of Introduced and Invasive Species - United States (Contiguous) and Global Register of Introduced and Invasive Species - Alaska, United States always show the same number of occurrences.  From what I can tell, both show the sum of the occurrences in the two areas.

Example: https://www.gbif.org/species/5420852

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/81f05fd73d3f780bf7483db7ce9ac73e:b6730b11fe072b5611c91fab8377364c1bb3464a26673b4f6f580adf4e1a3f427a9f45c29faae906110c564bca4590d96d96773292e10109b77edc29e1f65f84)
System: Firefox 97.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/species/5420852
Window size: width 1781 - height 1225
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-03-08T13:22:52.554Z',to:'2022-03-08T13:28:52.554Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-03-08T13:22:52.554Z',to:'2022-03-08T13:28:52.554Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by nonenmac** [comment]
The text I see for the above example (Daphne mezereum) is:

RECORDED AS INVASIVE IN 2 COUNTRIES OR ISLANDS
Recorded as introduced in | According to | Evidence of impact | Occurrences in GBIF
United States of America | Global Register of Introduced and Invasive Species - United States (Contiguous) | No | 459 occurrences
United States of America | Global Register of Introduced and Invasive Species - Alaska, United States | No | 459 occurrences

I think there are actually only 2 occurrences in Alaska

**Comment by MortenHofft** [comment]
This indeed looks like a mistake. It looks to me like the issue is a misunderstanding.
The way we generate this list is somewhat peculiar and somewhat fragile. We rely on the keywords provided in the published dataset. I've described details here https://github.com/gbif/portal16/issues/883

In this case the checklist about Alaska is labelled as being about all of US - this should be fixed in the dataset metadata

**Comment by ahahn-gbif** [comment]
An oversight on my part, apologies - handling of these checklists is indeed a bit of a special case. Recommended change on the side of the contributing datasets: update the keywords
-	for Hawaii, to: country_US-HI
-	for Alaska, to: country_US-AK

For verification, we will also need to check that after the update, all three lists still show here: https://www.gbif.org/dataset/search?keyword=country_US (as filtered in the "Alien Species" tab on the country page, https://www.gbif.org/country/US/summary)

**Comment by MortenHofft** [comment]
Please provide both keywords. For the country as well as the subdivision.
for Hawaii, to: `country_US` + `country_US-HI`
for Alaska, to: `country_US` + `country_US-AK`

We do not use the subdivision for anything at this point but to notify us NOT show an occurrence count (which would be for the country as a whole)

**Comment by ahahn-gbif** [comment]
Update verified and working as expected - thanks to all!

**Comment by nonenmac** [comment]
Just a note that the numbers and place names are still misleading.  The number and list for "Global Register of Introduced and Invasive Species - United States (Contiguous)" still include all of the Alaska and Hawaii occurrences. It seems like US-contiguous should be treated like the Alaska and Hawaii lists and say "unknown".  Then there could be a United States item that would include the whole list.

**Comment by nonenmac** [comment]
Maybe @asimpson-usgs can weigh in here.  As I noted yesterday, including all United States occurrences in the list and occurrence count for United States (Contiguous) doesn't seem right to met.  United States (Contiguous)  should be at the same level as Alaska and Hawaii.  The way this worked before this fix actually made more sense, even though is was confusing.

**Comment by asimpson-usgs** [comment]
@nonenmac , I think you are correct. The three datasets as submitted are sub-country level. I think I should generate (from the original [umbrella dataset](https://doi.org/10.5066/P95XL09Q)) a country level dataset that eliminates duplicates. I would retain the sublists as is, changing the metadata of the CONUS dataset to add the term `country_US-CONUS` (`country_US-AK` and `country-US-HI` are not ISO codes, and I cannot find a 2-letter code for CONUS). It will take me some time to do that, however, and I'd like to know that ISSG agrees with this approach before I start munging. I'm thinking Shyama Pagad (I don't know her GitHub login) or GBIF colleagues who have been in on this conversation, Tim Hirsch and Dmitri Schigel. @timhirsch @dschigel. And obviously @MortenHofft too.

**Comment by nonenmac** [comment]
@asimpson-usgs , I think using CONUS would be confusing, as it normally refers to Continental US (contiguous/conterminous US + Alaska), Or is that what you intend for that list?

**Comment by asimpson-usgs** [comment]
Huh. I always thought CONUS did not include Alaska, but I see now the CO of CONUS is often continental. We have used L48 in our abbreviation (lower 48 states), so maybe that is an (inaccurate) option, `country_US-L48`? 
GRIIS uses the term contiguous US, (while USGS prefers conterminous US and this article sums up why: [https://writingexplained.org/contiguous-vs-continuous-difference)](https://writingexplained.org/contiguous-vs-continuous-difference)).
This government report uses CONUS to mean conterminous US: [https://carbon2018.globalchange.gov/chapter/appendix-f/ ](https://carbon2018.globalchange.gov/chapter/appendix-f/), so the key is really in the definition, perhaps.

**Comment by asimpson-usgs** [comment]
@nonenmac  , I have explored how to create/generate a country level dataset from the three sub-country level datasets of the United States of America (conterminous US, Alaska, and Hawaii) and have concluded it is not trivial nor simply removing duplicates. This is because some species that are invasive in one dataset are native in in another, for example, the American bull frog (_Lithobates catesbeianus_) is invasive in Hawaii and native in the conterminous US.
Therefore, I will leave these three datasets as all being sub-country level. Concerning the proper metadata abbreviation for the conterminous or contiguous United States, in my web search only the abbreviation "CUS" has been used exclusively (at least so far) for "Conterminous United States". 
I plan to re-publish the Conterminous United States dataset, AKA United States (Contiguous), with two locational metadata terms (like Alaska and Hawaii already have). Each sub-country level dataset will have the following locational metadata terms attached:
Alaska: `country_US`, `country_US-AK`
Hawaii: `country_US`, `country_US-HI`
United States (Contiguous): `country_US`, `country_US-CUS`
Feedback, as always, is welcomed.
